// Generated by CoffeeScript 1.6.3
require.config({
  shim: {
    underscore: {
      exports: '_'
    },
    backbone: {
      deps: ['jquery', 'underscore'],
      exports: 'Backbone'
    },
    handlebars: {
      exports: 'Handlebars'
    },
    'jqueryui/jquery-ui': ['jquery']
  },
  paths: {
    jquery: '../bower_components/jquery/jquery',
    jqueryui: '../bower_components/jquery-ui/ui/',
    underscore: '../bower_components/lodash/lodash',
    backbone: '../bower_components/backbone/backbone',
    drizzle: '../bower_components/drizzlejs',
    text: '../bower_components/requirejs-text/text',
    handlebars: '../bower_components/handlebars/handlebars'
  }
});

define(['jquery', 'drizzle/drizzle', 'jqueryui/jquery-ui'], function($, Drizzle) {
  var app;
  app = window.app = new Drizzle.Application();
  app.global.applicationName = 'Drizzle Demos';
  return $(function() {
    return app.chain(app.show('simple:main/viewport'), function(viewport) {
      return viewport.regions.sidebar.show('main/menu');
    });
  });
});
