// Generated by CoffeeScript 1.7.1
require.config({
  baseUrl: 'scripts',
  paths: {
    text: '../bower_components/requirejs-text/text',
    jquery: '../bower_components/jquery/dist/jquery.min',
    drizzle: 'drizzlejs/drizzle',
    handlebars: '../bower_components/handlebars/handlebars'
  },
  shim: {
    handlebars: {
      exports: 'Handlebars'
    }
  }
});

require(['drizzle'], function(D) {
  var app;
  window.app = app = new D.Application();
  return app.show('viewport').done(function(viewport) {
    var content, sidebar, top, _ref;
    _ref = viewport.regions, top = _ref.top, sidebar = _ref.sidebar, content = _ref.content;
    top.show('main/top');
    sidebar.show('main/sidebar');
    return content.show('main/content');
  });
});
