// Generated by CoffeeScript 1.6.3
define(['jquery', 'underscore', 'config'], function($, _, config) {
  var defaults, key, merged, value, _ref;
  defaults = {
    development: true,
    cache: true,
    scriptRoot: 'app',
    urlRoot: '',
    urlSuffix: '',
    attributesReferToId: ['for', 'data-target', 'data-parent'],
    fileNames: {
      module: 'index',
      templates: 'templates',
      view: 'view-',
      template: 'template-',
      handler: 'handler-',
      model: 'model-',
      collection: 'collection-'
    }
  };
  merged = _.extend({}, defaults, config);
  _ref = defaults.fileNames;
  for (key in _ref) {
    value = _ref[key];
    if (!(key in merged.fileNames)) {
      merged.fileNames[key] = value;
    }
  }
  return merged;
});
