// Generated by CoffeeScript 1.6.3
define({
  layout: function(app, Handlebars, options) {
    if (this.View.isLayout) {
      return options.fn(this);
    } else {
      return '';
    }
  },
  view: function(app, Handlebars, name, options) {
    if (this.View.isLayout || this.View.name !== name) {
      return '';
    }
    return options.fn(this);
  }
});
