// Generated by CoffeeScript 1.6.3
define({
  separatedTemplate: true,
  items: [
    {
      name: 'foo',
      region: 'first'
    }, {
      name: 'bar',
      region: 'second'
    }
  ],
  models: {
    item: 'path'
  },
  collections: {
    items: 'path'
  }
});
