// Generated by CoffeeScript 1.6.3
(function() {
  define({
    adjustData: function(data) {
      data.b = 'bbb';
      return data;
    },
    beforeRender: function() {
      return console.log('beforeRender options');
    },
    afterRender: function() {
      return console.log('afterRender options');
    }
  });

}).call(this);
