// Generated by CoffeeScript 1.6.3
(function() {
  var __slice = [].slice;

  define({
    events: {
      'click btn': 'buttonClicked',
      'click check-*': 'checkClicked'
    },
    bind: {
      item: 'sync#render'
    },
    handlers: {
      buttonClicked: function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return console.log(args, 'args');
      },
      checkClicked: function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return console.log(args, 'args2');
      }
    }
  });

}).call(this);
