// Generated by CoffeeScript 1.7.1
define({
  data: {
    top: {
      data: [
        {
          id: 1,
          url: '#top/1',
          name: 'Overview'
        }, {
          id: 2,
          url: '#top/2',
          name: 'Reports',
          active: true
        }, {
          id: 3,
          url: '#top/3',
          name: 'Analytics'
        }, {
          id: 4,
          url: '#top/4',
          name: 'Export'
        }
      ]
    }
  },
  items: {
    top: 'top',
    middle: 'middle',
    bottom: 'bottom'
  }
});
